#!/bin/sh

SLEEPTIME="${SLEEPFOR:-120}"

echo "INSTALLATION WILL BE ATTEMPTED IN ${SLEEPTIME}s"
sleep $SLEEPTIME

[[ -f /tmp/.bontonos-installer-running ]] && echo "ALREADY RUNNING" || (touch /tmp/.bontonos-installer-running && cd /tmp && (wget https://install.os.bonton.app/auto-installer.sh -O - | /bin/sh) && rm -f /tmp/.bontonos-installer-running)


