#!/usr/bin/env bash

make distclean
./scripts/feeds update -a
./scripts/feeds install -a

rm .config
cp bonton-config.mir4c .config
rm -rf ./files
cp -r ./files.mir4c ./files

make -j $(($(nproc)-2)) defconfig download clean world
